# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Cheston Chow
title: Python Programmer / Data Analyst
email: cheston.chow@gmail.com 
website: cchw.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  cchw
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: cchw
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Unix and QA Engineer with over 10 years of experience supporting mission-critical systems in a Linux/Unix environment. Skilled in scripting (Bash, Python, SQL), with strong background in system testing, release management, and troubleshooting. Proven ability to document processes, train staff, and translate complex technical issues into actionable solutions. Hands-on experience in automation, monitoring, and performance optimization.

  I am most skilled in: <mark>Problem solving</mark> and <mark>Getting things done</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 1. My awesome project
        link: github.com/cchw
        link_text: github.com/cchw 
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/cchw
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>Data Science</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
     
      # - layout: top-middle
      #   description: |
      #     ---

      - layout: top-middle
        title: 2. My other awesome project
        link: github.com/cchw
        link_text: github.com/cchw 
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/cchw
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>Data Science</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.


  - title: Skills
    layout: text
    content: |
      **Programming**:&nbsp;&nbsp;&nbsp;&nbsp; Python · SQL · Bash · Lua  
      **Databases**:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MySQL · SQLite · DuckDB · Sybase · Oracle  
      **Tools**:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; tableau, git · GitHub · Docker · pyenv · uv · Unix CLI, jq  
      **Networking**:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; TCP/IP · FIX Protocol · Subnetting · VPN · SNMP


  # - title: Skills
  #   layout: text
  #   content: |
  #     <pre>
  #     Programming     Python · SQL · Bash · Lua
  #     Databases       MySQL · SQLite · DuckDB · Sybase · Oracle
  #     Tools           git · GitHub · Docker · pyenv · uv · Unix CLI
  #     Networking      TCP/IP · FIX Protocol · Subnetting · VPN · SNMP
  #     </pre>
  #
  # - title: Skills
  #   layout: text
  #   content: |
  #     | **Category**   | **Skills** |
  #     |----------------|------------|
  #     | Programming    | Python, SQL, Bash, Lua |
  #     | Databases      | MySQL, SQLite, DuckDB, Sybase, Oracle |
  #     | Tools          | git, GitHub, Docker, pyenv, uv, Unix CLI |
  #     | Networking     | TCP/IP, FIX Protocol, Subnetting, VPN, SNMP |


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Lucky Enterprise, Inc.
        link: # boringcompany.com
        # link_text: boringcompany.com
        sub_title: Automation Engineer / Assistant Property Manager
        caption: July 2024 - August 2025
        # quote: >
        #    Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Designed and automated Unix shell and Python scripts to streamline operational processes, reduced manual workload, and increased reliability.
          - Built and maintained data collection pipelines (Python, pandas, BeautifulSoup, APIs) ensuring accuracy and timely delivery of economic and operational datasets.

      - layout: left
        title: Virtua Financial, Inc.
        link: https://www.virtu.com/
        link_text: virtu.com
        sub_title: Quality Assurance Engineer
        caption: March 2017 - January 2020
        # quote: >
        #    Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Led QA testing of mission-critical trading matching engine, (POSIT ATS), developed and executing test cases across Linux environments to validate functionality, performance and reliability.
          - Automated testing workflows using Python, SQL, Bash scripts, improving defect detection and reducing release cycle time.
          - Migrated backend application servers from Solaris to Linux, optimizing performance and standardizing environments.
          - Oversaw our global QA team, coordinated with global engineers, trained junior staff and documented procedures.

      - layout: left
        title: Investment Technology Group
        link: https://en.wikipedia.org/wiki/Investment_Technology_Group
        link_text: Investment Technology Group
        sub_title: Fix Integration Specialist, Application Support
        caption: October 2010 - March 2017
        # quote: >
        #    Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Configured and maintained FIX connectivity between client OMS and internal trading, matching and routing engines, ensuring secure and reliable integration.
          - Performed system-level testing, troubleshooting, and log analysis and resolve connectivity and routing issues in real time.
          - Automated trade reporting pipelines with shell scripts, Python, and SQ, leveraging cron jobs.
          - Executed releases of core trading components in Linux environments, managing change tickets and developed installation scripts.
          - Performed production release of the FIX routing engine and the dark pool matching engine, coordinating deployments, writing install scripts, and validating roll-out success.
          - Monitored critical End-of-Day batch jobs, analyzing logs and system performance.
          - Authored support run-books and collaborated with infrastructure teams to document processes.


  - title: Education
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Stony Brook University
        sub_title: Stony Brook, NY
        link: https://www.stonybrook.edu
        # link_text: Stony Brook Unversity
      - layout: middle
        description: | # this will include new lines to allow paragraphs
          - *Bachelor of Science in [Applied Mathematics and Statistics](https://www.stonybrook.edu/commcms/ams/)*
          - *Bachelor of Arts in [Economics](https://www.stonybrook.edu/commcms/economics/)*


  # - title: Education # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: Harvard University
  #       caption: 2010 - 2013
  #       sub_title: BSc Computer Science
  #       quote: >
  #         Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
  #       description: | # this will include new lines to allow paragraphs
  #         During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
  #
  #         I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
  #

# Footer
# footer_show_references: true
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
